config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :favorite_memes, only: [:create, :destroy]

  get "auth/facebook/callback", to: "sessions#create"
  get "auth/failure", to: redirect('/')

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "memes#index"
  resources :memes do
    member do
      post "like" => "memes#vote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/meme.rb
class Meme < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth['uid'], provider:  auth['provider'])
    user.email = "#{auth['uid']}@#{auth['provider']}.com"
    user.password = auth['uid']
    user.name = auth['info']['name']
    user.username = auth['info']['name']
    user.save
    user
  end

  EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }

  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX

  validates :password, :presence => true,
                     :confirmation => true,
                     :length => {:within => 6..40},
                     :on => :create

  validates :password, :confirmation => true,
                     :length => {:within => 6..40},
                     :allow_blank => true,
                     :on => :update

  acts_as_voter
  has_many :memes
  has_many :favorites
  has_many :favorite_memes, through: :favorites, source: :favorited, source_type: 'Meme'
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  def show
    @user = User.find(params[:id])
    render template: "users/show"
  end

  private

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    username = user_params.delete(:username)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.username = username
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end

  def permit_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/favorite_memes_controller.rb
class FavoriteMemesController < ApplicationController

  before_action :set_meme
  def create
    if Favorite.create(favorited: @meme, user: current_user)
      redirect_to current_user
      flash[:error] = "You favorited that meme"
    else
      redirect_to @meme
      flash[:error] = "Something went wrong..."
    end
  end

  def destroy
    Favorite.where(favorited_id: @meme.id, user_id: current_user.id).first.destroy
    redirect_to current_user
  end

  private

  def set_meme
    @meme = Meme.find(params[:meme_id] || params[:id])
  end

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  respond_to :js
  def index
    @meme = Meme.all.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  def show
    @meme = Meme.find(params[:id])
  end

  def new
    @meme = Meme.new
    if signed_out?
      redirect_to sign_up_path
    end
  end

  def create
    @meme = Meme.new(meme_params)
    if @meme.save
      redirect_to @meme
    else
      @meme = Meme.create
      flash[:error] = "Your submission could not be sent. Please try again."
      redirect_to new_meme_path
    end
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.delete
    redirect_to root_path
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  def vote
    @meme = Meme.find(params[:id])
    if !current_user.liked? @meme
      @meme.liked_by current_user
    elsif current_user.liked? @meme
      @meme.unliked_by current_user
    end

  end

  def update
    @meme = Meme.find(params[:id])
    @meme.update_attributes(meme_params)
    redirect_to meme_path(@meme)
  end

  private
  def meme_params
    params.require(:meme).permit(:title, :image, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
    if request.env['omniauth.auth']
      user = User.create_with_omniauth(request.env['omniauth.auth'])
      sign_in user
      redirect_to user_path(user.id)
    else
      user = User.find_by_email(params[:email])
      user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemeWars</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <nav>
        <div class="nav-wrapper blue lighten-4">
          <a href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="material-icons">menu</i>
          </a>
          <%= link_to image_tag('meme_logo.png'), root_path, class: "brand-logo" %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
              <%= link_to "Memes", memes_path %>
            </li>
            <li>
              <%= link_to "Post", new_meme_path %>
            </li>
            <% if signed_in? -%>
            <li><%= link_to current_user.username, user_path(current_user)%></li>
            <li><%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "waves-effect waves-light btn-flat"%></li>
          <% else -%>
            <li><%= link_to t(".sign_in"), sign_in_path %></li>
            <li><%= link_to t(".sign_up"), sign_up_path %></li>
            <% end -%>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li>
              <%= link_to "Memes", memes_path %>
            </li>
            <li>
              <%= link_to "Post", new_meme_path %>
            </li>
            <% if signed_in? -%>
            <li><%= link_to current_user.username, user_path(current_user)%></li>
            <li><%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "waves-effect waves-light btn-flat"%></li>
          <% else -%>
            <li><%= link_to t(".sign_in"), sign_in_path %></li>
            <li><%= link_to t(".sign_up"), sign_up_path %></li>
            <% end -%>
          </ul>
        </div>
      </nav>
    </div>
    <header></header>

    <div id="flash">
      <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
      <% end %>
    </div>

    <%= yield %>
    <footer class="page-footer blue lighten-4">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h4 class="white-text">MemeWars</h4>
            <p class="grey-text text-lighten-4">A site for sharing memes with your friends.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h4 class="white-text">Links</h4>
            <ul id="nav-mobile">
              <li>
                <a href="https://github.com/ibi8588">GitHub</a>
              </li>
              <li>
                <a href="https://www.linkedin.com/in/ibrahim-aldridge-6b0b932b/">LinkedIn</a>
              </li>
              <li>
                <a href="https://www.facebook.com/ibrahim.aldridge">Facebook</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container"></div>
      </div>
    </footer>
  </body>
</html>

app/views/memes/edit.html.erb
<%= image_tag('edit-meme.png', class: "edit-meme") %>

<%= form_for @meme do |form| %>
  <div class="row">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">description</i>
          <%= form.label :title %>
          <%= form.text_field :title, type: 'text', placeholder: "title" %>
        </div>
      </div>
  </div>
  <div class="row">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">image</i>
          <%= form.file_field :image %>
        </div>
      </div>
  </div>
<%= form.hidden_field :user_id, :value => "#{current_user.id}" %>
<%= form.submit "Post Meme", class: 'btn'%><br>
<% end %>

app/views/memes/index.html.erb
<% @meme.each do |meme| %>
<div class="row">
  <div class="col s12 m7 offset-m3">
    <div class="card hoverable">
      <div class="card-image">
        <%= image_tag(meme.image) %>
      </div>
      <div class="card-content">
        <p><%= meme.title %></p>
      </div>
        <%= link_to( meme_path(meme)) do %>
        <div class="card-action">
          <span>
            <p>
              <i class="material-icons prefix view-meme">photo</i>View</p>
          </span>
      </div>
      <% end %>
      <div class="card-action">
        Posted by
        <%= link_to( meme.user.username, user_path(meme.user)) %>
      </div>
      <% if current_user %>
        <% fav = current_user.favorites.find_by(favorited_id: meme.id) %>
          <% if fav %>
            <%= link_to favorite_meme_path(meme.id), method: :delete do %>
            <div class="card-action">
              <span>
                <p>
                  <i class="material-icons prefix unfavorite">favorite_border</i>Remove From Favorites</p>
              </span>
            </div>
            <% end %>
        <% else %>
          <%= link_to favorite_memes_path(meme_id: meme), method: :post do %>
          <div class="card-action">
            <span>
              <p>
                <i class="material-icons prefix favorite">favorite</i>Favorite</p>
            </span>
          </div>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to like_meme_path(meme), class: "like-btn", method: :post, remote: :true do %>
        <div>
          <span>
            <p>
              <i class="material-icons prefix thumb-up">thumb_up</i>Like</p>
          </span>
        </div>
      <% end %>
      <span class="likes-count"><%= meme.get_upvotes.size %></span>
      <div class="card-action">
        Posted at
        <%= meme.created_at.strftime('%c') %>
      </div>
      <%= social_share_button_tag(meme.title) %>
    </div>
  </div>
</div>
<% end %>
<%=  page_entries_info @meme %>
<%= will_paginate @meme %>

app/views/memes/new.html.erb
<%= image_tag('new-meme.png', class: "new-meme-image") %>

<%= form_for @meme do |form| %>
<div class="row">
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">description</i>
        <%= form.label :title %>
        <%= form.text_field :title, type: 'text', placeholder: "title" %>
      </div>
    </div>
</div>
<div class="row">
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">image</i>
        <%= form.file_field :image %>
      </div>
    </div>
</div>
<%= form.hidden_field :user_id, :value => "#{current_user.id}" %>
<%= form.submit "Post Meme", class: 'btn'%>
<% end %>

app/views/memes/show.html.erb
<%= image_tag('show-meme.png', class: "meme-show") %>
  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <%= image_tag (@meme.image) %>
        </div>
        <div class="card-content">
          <p><%= @meme.title %></p>
        </div>
        <div class="card-action">
          Posted by  <%= link_to( @meme.user.username, user_path(@meme.user)) %>
        </div>
        <% if current_user %>
          <% fav = current_user.favorites.find_by(favorited_id: @meme.id) %>
            <% if fav %>
              <%= link_to favorite_meme_path(@meme.id), method: :delete do %>
              <div class="card-action">
                <span>
                  <p>
                    <i class="material-icons prefix unfavorite">favorite_border</i>Remove From Favorites</p>
                </span>
              </div>
              <% end %>
          <% else %>
            <%= link_to favorite_memes_path(meme_id: @meme), method: :post do %>
            <div class="card-action">
              <span>
                <p>
                  <i class="material-icons prefix favorite">favorite</i>Favorite</p>
              </span>
            </div>
            <% end %>
          <% end %>
        <% end %>
        <%= link_to like_meme_path(@meme), class: "like-btn", method: :post, remote: :true do %>
        <div>
          <span><p><i class="material-icons prefix thumb-up">thumb_up</i></p></span>
        </div>
        <% end %>
        <span class="likes-count"><%= @meme.get_upvotes.size %></span>
        <div class="card-action">
          Posted at <%= @meme.created_at.strftime('%c') %>
        </div>
        <%= social_share_button_tag(@meme.title) %>
      </div>
        <div class="card-action">
          <% if signed_in? && current_user.id ==  @meme.user_id %>
          <%= button_to "Edit Meme", edit_meme_path, method: "get", action: "edit", class: "btn" %><br>
          <%= button_to "Delete Meme", "/memes/#{@meme.id}", method: "delete", action: "destroy", class: "btn",  data: {confirm: "Are you sure you want to delete this awesome meme?"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/memes/vote.js.erb
<% if current_user.liked? @meme %>
  $('.like-btn').addClass('liked');
  <% else %>
  $('.like-btn').addClass('like-btn');
  <% end %>
$('.likes-count').html("<%=@meme.get_upvotes.size %>");

app/views/shared/_meme_index.html.erb
<% @meme.each do |meme| %>
        <div class="row">
          <div class="col s12 m7 offset-m3">
            <div class="card hoverable">
              <div class="card-image">
                <%= image_tag src=meme.image %>
              </div>
              <div class="card-content">
                <p><%= meme.title %></p>
              </div>
              <div class="card-action">
                <%= link_to("View Meme", meme_path(meme)) %>
              </div>
              <div class="card-action">
              Posted by  <%= link_to( meme.user.username, user_path(meme.user)) %>
              </div>
              <% if current_user %>
                <% fav = current_user.favorites.find_by(favorited_id: meme.id) %>
                <% if fav %>
                    <%= link_to favorite_meme_path(meme.id), method: :delete do %>
                    <div class="card-action">
                        <span><p><i class="material-icons prefix unfavorite">favorite_border</i>Remove From Favorites</p></span>
                  </div>
                  <% end %>
                  <% else %>
                    <%= link_to favorite_memes_path(meme_id: meme), method: :post do %>
                    <div class="card-action">
                      <span><p><i class="material-icons prefix favorite">favorite</i>Favorite</p></span>
                    </div>
                    <% end %>
                  <% end %>
              <% end %>
              <%= link_to like_meme_path(meme), class: "like-btn", method: :post, remote: :true do %>
              <div>
                <span><p><i class="material-icons prefix thumb-up">thumb_up</i>Like</p></span>
              </div>
              <% end %>
              <span class="likes-count"><%= meme.get_upvotes.size %></span>
              <div class="card-action">
                Posted at <%= meme.created_at.strftime('%c') %>
              </div>
              <%= social_share_button_tag(meme.title) %>
            </div>
          </div>
        </div>
  <% end %>

app/views/shared/_user_memes.html.erb
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <%= image_tag meme.image %>
      </div>
      <div class="card-content">
        <p><%= meme.title %></p>
      </div>
      <div class="card-action">
        Posted by
        <%= link_to( meme.user.username, user_path(meme.user)) %>
      </div>
      <% if current_user %>
      <% fav = current_user.favorites.find_by(favorited_id: meme.id) %>
      <% if fav %>
      <div class="card-action">
        <%= link_to( "Remove from Favorites", favorite_meme_path(meme.id), method: :delete) %>
      </div>
    <% else %>
      <div class="card-action">
        <%= link_to( "Add to Favorites", favorite_memes_path(meme_id: meme), method: :post) %>
      </div>
      <% end %>
      <% end %>
      <% if signed_in? && current_user.id ==  meme.user_id %>
      <div class="card-action">
        <%= button_to "Edit Meme", edit_meme_path(meme), method: "get", action: "edit", class: "btn" %><br>
        <%= button_to "Delete Meme", "/memes/#{meme.id}", method: "delete", action: "destroy", class: "btn",  data: {confirm: "Are you sure you want to delete this awesome meme?"} %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <%= form.label :username %>
        <%= form.text_field :username, type: 'text', placeholder: "Username" %>
      </div>
    </div>
</div>

<div class="row">
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">email</i>
        <%= form.label :email %>
        <%= form.text_field :email, type: 'email', placeholder: "Email" %>
      </div>
    </div>
</div>

<div class="row">
    <div class="row">
      <div class="input-field col s6">
      <i class="material-icons prefix">security</i>
      <%= form.label :password %>
      <%= form.password_field :password %>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
<%= image_tag('sign-up.png', class: "sign-up-image") %>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <br><%= form.submit class: 'btn'%><br>
    </div>

    <div class="other-links">
      <br><%= link_to t(".sign_in"), sign_in_path, class: 'btn' %><br>
    </div>
  <% end %>
  <div class="facebook-sign-in">
    <br><%= link_to "Sign in with Facebook", "https://www.facebook.com/v2.10/dialog/oauth?client_id=#{Rails.application.secrets.facebook_app_id}&redirect_uri=#{ auth_facebook_callback_url }", class: "btn" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="account-welcome">
  <span class="welcome-span">Welcome, <%= @user.username %></span>
</div>
<%= image_tag('meme-posts.png', class: "meme-posts-image") %>
<% @user.memes.each do |meme| %>
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <%= image_tag(meme.image)%>
      </div>
      <div class="card-content">
        <p><%= meme.title %></p>
      </div>
      <div class="card-action">
        Posted by
        <%= link_to( meme.user.username, user_path(meme.user)) %>
      </div>
      <% if current_user %>
        <% fav = current_user.favorites.find_by(favorited_id: meme.id) %>
          <% if fav %>
            <%= link_to favorite_meme_path(meme.id), method: :delete do %>
            <div class="card-action">
              <span>
                <p>
                  <i class="material-icons prefix unfavorite">favorite_border</i>Remove From Favorites</p>
              </span>
            </div>
            <% end %>
        <% else %>
          <%= link_to favorite_memes_path(meme_id: meme), method: :post do %>
          <div class="card-action">
            <span>
              <p>
                <i class="material-icons prefix favorite">favorite</i>Favorite</p>
            </span>
          </div>
          <% end %>
        <% end %>
      <% end %>
      <% if signed_in? && current_user.id ==  meme.user_id %>
      <div class="card-action">
        <%= button_to "Edit Meme", edit_meme_path(meme), method: "get", action: "edit", class: "btn" %><br>
        <%= button_to "Delete Meme", "/memes/#{meme.id}", method: "delete", action: "destroy", class: "btn",  data: {confirm: "Are you sure you want to delete this awesome meme?"} %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>
<% end %>

<%= image_tag('favorite-memes.png', class: "favorite-meme-image") %>

<% @user.favorite_memes.each do |meme| %>
<div class="row">
<div class="col s12 m7">
  <div class="card">
    <div class="card-image">
      <%= image_tag(meme.image) %>
    </div>
    <div class="card-content">
      <p><%= meme.title %></p>
    </div>
    <div class="card-action">
      Posted by
      <%= link_to( meme.user.username, user_path(meme.user)) %>
    </div>
    <% if current_user %>
      <% fav = current_user.favorites.find_by(favorited_id: meme.id) %>
        <% if fav %>
          <%= link_to favorite_meme_path(meme.id), method: :delete do %>
          <div class="card-action">
            <span>
              <p>
                <i class="material-icons prefix unfavorite">favorite_border</i>Remove From Favorites</p>
            </span>
          </div>
          <% end %>
      <% else %>
        <%= link_to favorite_memes_path(meme_id: meme), method: :post do %>
        <div class="card-action">
          <span>
            <p>
              <i class="material-icons prefix favorite">favorite</i>Favorite</p>
          </span>
        </div>
        <% end %>
      <% end %>
    <% end %>
    <div class="card-action">
      <% if signed_in? && current_user.id ==  meme.user_id %>
      <%= button_to "Edit Meme", edit_meme_path, method: "get", action: "edit", class: "btn" %><br>
      <%= button_to "Delete Meme", "/memes/#{meme.id}", method: "delete", action: "destroy", class: "btn",  data: {confirm: "Are you sure you want to delete this awesome meme?"} %>
      <% end %>
    </div>
  </div>
</div>
</div>
<% end %>